apiVersion: v1
kind: Pod
metadata:
  name: portal-de-noticias
spec:
  containers:
    - name: portal-de-noticias
      image: aluracursos/portal-noticias:1
      resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"