apiVersion: v1
kind: Service
metadata:
  name: portal-noticias-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: portal-noticias
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80